version: '3.8'

services:
  market-data-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./config:/app/config
    environment:
      - IG_USERNAME=${IG_USERNAME}
      - IG_PASSWORD=${IG_PASSWORD}
      - IG_API_KEY=${IG_API_KEY}
      - IG_ACC_TYPE=${IG_ACC_TYPE:-DEMO}
      - REDIS_URL=redis://redis:6379
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=agents_platform
      - DB_USER=admin
      - DB_PASSWORD=secure_agents_password
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    restart: unless-stopped

volumes:
  redis_data:
